name: build and deploy release
on:
  release:
    types: [published]
jobs:
  windows-build:
    if: github.repository == 'QW-Group/ezquake-source'
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: msbuild-x64
        buildPreset: msbuild-x64-release

    - name: Create checksum
      run: |
        md5sum ezquake.exe > ezquake.md5

    - name: Setup SSH
      env:
        SSH_AUTH_SOCK: C:\ssh_agent.sock
      shell: msys2 {0}
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
    - name: Set date
      shell: msys2 {0}
      run: |
        export TZ=CET-1CEST
        echo "DATE=$(date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV
    - name: Deploy
      env:
        SSH_AUTH_SOCK: C:\ssh_agent.sock
      shell: msys2 {0}
      run: |
           mkdir -p upload/releases/${{ github.ref_name }}/windows/${{ matrix.platform }}/${{ matrix.config }}
           mkdir -p upload/releases/latest/windows/${{ matrix.platform }}/${{ matrix.config }}
           cp ezquake.exe upload/releases/${{ github.ref_name }}/windows/${{ matrix.platform }}/${{ matrix.config }}/ezquake.exe
           cp ezquake.md5 upload/releases/${{ github.ref_name }}/windows/${{ matrix.platform }}/${{ matrix.config }}/ezquake.md5
           cp ezquake.exe upload/releases/latest/windows/${{ matrix.platform }}/${{ matrix.config }}/ezquake.exe
           cp ezquake.md5 upload/releases/latest/windows/${{ matrix.platform }}/${{ matrix.config }}/ezquake.md5
           sftp -rp -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -P ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:/releases <<< $'put -rp upload/releases/*'

  linux-build:
    if: github.repository == 'QW-Group/ezquake-source'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       target: [linux-x86_64]
       include:
         - target: linux-x86_64
           platform: x86_64
    container:
      image: debian:testing
      options: --privileged

    steps:
    - name: Install dependencies
      run: apt-get -qy update && apt-get -qy install curl file libfuse2 git make sudo git

    - name: Check out code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build
      run:  git config --global --add safe.directory $PWD && ./misc/appimage/appimage-manual_creation.sh

    - name: Create checksum
      run: |
           md5sum ezQuake-${{ matrix.platform }}.AppImage > ezQuake-${{ matrix.platform }}.AppImage.md5

    - name: Setup SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      shell: bash
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
    - name: Set date
      shell: bash
      run: |
        export TZ=CET-1CEST
        echo "DATE=$(date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV
    - name: Deploy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      shell: bash
      run: |
           mkdir -p upload/releases/${{ github.ref_name }}/linux
           mkdir -p upload/releases/latest/linux/${{ matrix.platform }}
           cp ezQuake-${{ matrix.platform }}.AppImage upload/releases/${{ github.ref_name }}/linux/ezQuake-${{ matrix.platform }}.AppImage
           cp ezQuake-${{ matrix.platform }}.AppImage.md5 upload/releases/${{ github.ref_name }}/linux/ezQuake-${{ matrix.platform }}.AppImage.md5
           cp ezQuake-${{ matrix.platform }}.AppImage upload/releases/latest/linux/${{ matrix.platform }}/ezQuake-${{ matrix.platform }}.AppImage
           cp ezQuake-${{ matrix.platform }}.AppImage.md5 upload/releases/latest/linux/${{ matrix.platform }}/ezQuake-${{ matrix.platform }}.AppImage.md5
           sftp -rp -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -P ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:/releases <<< $'put -rp upload/releases/*'
